import { describe, expect, test } from 'bun:test';
import { readdirSync, readFileSync, statSync } from 'node:fs';
import { join, relative } from 'node:path';
import { MCP_TOOL_CATALOG, jsonSchemaFor, readEstimate, schemaDigest, type McpToolDef } from '../mcp/tool-catalog.js';
import { allowedPolicies } from '../mcp/policies.js';
import { RETIRED_TOOL_NAMES, currentNameFor, isRetiredToolName, retiredNamesFor } from '../mcp/tool-names.js';
import { HANDOFF_TO_CATALOG } from '../dashboard/local-handoff-format.js';
import { READ_TOOL_NAMES } from '../dashboard/ui/src/store/mirror-tools.js';
import { READ_TOOL_SCHEMAS } from '../dashboard/ui/src/hybrid/read-tool-schemas.js';
import { MUTATING_TOOL_NAMES, READ_ONLY_TOOL_NAMES } from './mutation-audit.js';
import baseline from './fixtures/webmcp-tool-baseline.json';

/**
 * The WebMCP tool naming convention (specs/webmcp-tool-naming.md §1) enforced over the catalog, the collision rule
 * against chat tool names, and the invariants that say the rename changed nothing but names (I1, I1b, I11, I13, I14).
 * The baseline fixture was generated from the pre-rename catalog and is never regenerated by this change.
 */

// ── The convention ───────────────────────────────────────────────────────────

const STOP_WORDS = new Set('a an and by for from in into of on or the to with'.split(' '));

/** Stems, not whole segments: `judgements` must fail even though only `judgement` is listed (AR-P9). */
const BRITISH_STEMS = [
  'judgement', 'analyse', 'analysed', 'analyses', 'analysing', 'behaviour', 'cancell', 'catalogue', 'categoris',
  'centre', 'colour', 'defence', 'favour', 'labell', 'licence', 'modell', 'organis', 'summaris',
];

/** Words the trailing-`s` test misreads (status, analysis, ...). Empty today; each entry needs a one-line reason. */
const PLURALITY_EXCEPTIONS: Record<string, 'singular' | 'plural'> = {};

type Predicate = (def: Pick<McpToolDef, 'classification' | 'uiEffect'>) => boolean;
const isPageUi: Predicate = (d) => d.classification === 'page' && d.uiEffect === true;
/** One predicate per verb; a verb outside this table fails, and every def must satisfy its own verb's predicate. */
const VERB_PREDICATES: Record<string, Predicate> = {
  get: (d) => d.classification === 'read' || (d.classification === 'page' && d.uiEffect !== true),
  list: (d) => d.classification === 'read',
  search: (d) => d.classification === 'read',
  open: isPageUi,
  fill: isPageUi,
  set: (d) => d.classification === 'mutating',
  update: (d) => d.classification === 'mutating',
  categorize: (d) => d.classification === 'mutating',
  resolve: (d) => d.classification === 'mutating',
  create: (d) => d.classification === 'mutating',
  delete: (d) => d.classification === 'mutating',
  propose: (d) => d.classification === 'proposal',
};

function segments(name: string): { verb: string; object: string[] } {
  const [verb, ...object] = name.split('_');
  return { verb: verb!, object };
}

function pluralityOf(word: string): 'singular' | 'plural' {
  if (PLURALITY_EXCEPTIONS[word]) return PLURALITY_EXCEPTIONS[word]!;
  return word.endsWith('s') && !word.endsWith('ss') ? 'plural' : 'singular';
}

function britishStem(segment: string): string | undefined {
  return BRITISH_STEMS.find((stem) => segment.startsWith(stem));
}

function isArrayShape(shape: unknown): boolean {
  if (shape == null) return false;
  const s = shape as { _zod?: { def?: { type?: string } }; _def?: { type?: string; typeName?: string } };
  return (s._zod?.def?.type ?? s._def?.type) === 'array' || s._def?.typeName === 'ZodArray';
}

/** Why `def` breaks the convention, or null. Pure, so the self-tests below can feed it bad names. */
function namingViolation(def: Pick<McpToolDef, 'name' | 'classification' | 'uiEffect' | 'zodShape'>): string | null {
  const { name } = def;
  if (!/^[a-z]+(_[a-z]+){1,3}$/.test(name)) return 'N1 shape';
  if (name.length > 32) return 'N2 length';
  const { verb, object } = segments(name);
  const stop = object.find((o) => STOP_WORDS.has(o));
  if (stop) return `N3 stop word ${stop}`;
  const british = segments(name).object.concat(verb).find((s) => britishStem(s));
  if (british) return `N9 British spelling ${british}`;
  const predicate = VERB_PREDICATES[verb];
  if (!predicate) return `N4 verb ${verb} is not in the verb set`;
  if (!predicate(def)) return `N4 verb ${verb} does not fit classification ${def.classification}`;
  const last = object[object.length - 1]!;
  if (['list', 'search', 'fill'].includes(verb) && pluralityOf(last) !== 'plural') return `N5 ${last} should be plural`;
  if (['get', 'open', 'set', 'update', 'categorize', 'resolve', 'create', 'delete'].includes(verb) && pluralityOf(last) !== 'singular') {
    return `N6 ${last} should be singular`;
  }
  if (verb === 'propose') {
    const batch = isArrayShape(def.zodShape.items);
    if (batch !== (pluralityOf(last) === 'plural')) return `N7 ${last} must be ${batch ? 'plural' : 'singular'}`;
  }
  return null;
}

const byName = new Map(MCP_TOOL_CATALOG.map((d) => [d.name, d]));

describe('WebMCP naming convention (spec §1)', () => {
  test('catalog size and order are unchanged: 26 tools', () => {
    expect(MCP_TOOL_CATALOG).toHaveLength(26);
    expect(new Set(MCP_TOOL_CATALOG.map((d) => d.name)).size).toBe(26);
  });

  test('N1 shape: lower snake case, letters only, 2 to 4 segments', () => {
    for (const d of MCP_TOOL_CATALOG) expect(d.name, d.name).toMatch(/^[a-z]+(_[a-z]+){1,3}$/);
  });

  test('N2 length: at most 32 characters', () => {
    for (const d of MCP_TOOL_CATALOG) expect(d.name.length, d.name).toBeLessThanOrEqual(32);
  });

  test('N3 no stop words in the object', () => {
    for (const d of MCP_TOOL_CATALOG) expect(segments(d.name).object.filter((o) => STOP_WORDS.has(o)), d.name).toEqual([]);
  });

  test('N4 verb is in the verb set, and its predicate holds for the tool (both directions)', () => {
    for (const d of MCP_TOOL_CATALOG) {
      const { verb } = segments(d.name);
      expect(VERB_PREDICATES[verb], `${d.name}: verb ${verb} is not in the verb set`).toBeDefined();
      expect(VERB_PREDICATES[verb]!(d), `${d.name}: ${verb} vs ${d.classification}`).toBe(true);
    }
  });

  test('N4 reverse: every classification is reachable only through its listed verbs', () => {
    const verbsOf = (c: McpToolDef['classification']) => [...new Set(MCP_TOOL_CATALOG.filter((d) => d.classification === c).map((d) => segments(d.name).verb))].sort();
    expect(verbsOf('proposal')).toEqual(['propose']);
    expect(verbsOf('mutating').every((v) => ['set', 'update', 'categorize', 'resolve', 'create', 'delete'].includes(v))).toBe(true);
    expect(verbsOf('read').every((v) => ['get', 'list', 'search'].includes(v))).toBe(true);
    expect(verbsOf('page').every((v) => ['get', 'open', 'fill'].includes(v))).toBe(true);
  });

  test('N5 to N7 plurality of the last object segment', () => {
    for (const d of MCP_TOOL_CATALOG) {
      const { verb, object } = segments(d.name);
      const last = object[object.length - 1]!;
      if (['list', 'search', 'fill'].includes(verb)) expect(pluralityOf(last), d.name).toBe('plural');
      else if (verb === 'propose') expect(pluralityOf(last) === 'plural', d.name).toBe(isArrayShape(d.zodShape.items));
      else expect(pluralityOf(last), d.name).toBe('singular');
    }
    expect(Object.keys(PLURALITY_EXCEPTIONS)).toEqual([]);
  });

  test('N8 twins (names that differ only by a trailing s) share classification, minRole and defaultPolicy', () => {
    const names = new Set(MCP_TOOL_CATALOG.map((d) => d.name));
    const twins = MCP_TOOL_CATALOG.filter((d) => names.has(`${d.name}s`));
    expect(twins.map((d) => d.name)).toEqual(['propose_judgment']);
    for (const a of twins) {
      const b = byName.get(`${a.name}s`)!;
      expect([b.classification, b.minRole, b.defaultPolicy]).toEqual([a.classification, a.minRole, a.defaultPolicy]);
    }
  });

  test('N8b the twins differ in transports and exposure, so behavior must be keyed on those, never on the spelling', () => {
    const single = byName.get('propose_judgment')!;
    const batch = byName.get('propose_judgments')!;
    expect([single.exposure, single.transports.includes('http-mcp')]).toEqual(['declarative', false]);
    expect([batch.exposure, batch.transports.includes('http-mcp')]).toEqual(['imperative', true]);
  });

  test('N9 no British spellings (stem match), and the old name provably fails', () => {
    for (const d of MCP_TOOL_CATALOG) expect(segments(d.name).object.concat(segments(d.name).verb).filter((s) => britishStem(s)), d.name).toEqual([]);
    expect(namingViolation({ name: 'propose_judgements', classification: 'proposal', zodShape: byName.get('propose_judgments')!.zodShape })).toMatch(/^N9/);
  });

  test('the whole predicate accepts every catalog name and refuses known-bad ones', () => {
    for (const d of MCP_TOOL_CATALOG) expect(namingViolation(d), d.name).toBeNull();
    const shape = {};
    expect(namingViolation({ name: 'tax_flag', classification: 'mutating', zodShape: shape })).toMatch(/^N4/);
    expect(namingViolation({ name: 'navigate_to_tab', classification: 'page', uiEffect: true, zodShape: shape })).toMatch(/^N3|^N4/);
    expect(namingViolation({ name: 'list_transaction', classification: 'read', zodShape: shape })).toMatch(/^N5/);
    expect(namingViolation({ name: 'get_transactions', classification: 'read', zodShape: shape })).toMatch(/^N6/);
    expect(namingViolation({ name: 'set_x_y_z_w', classification: 'mutating', zodShape: shape })).toMatch(/^N1/);
    expect(namingViolation({ name: 'get_thing', classification: 'mutating', zodShape: shape })).toMatch(/^N4/);
  });
});

// ── Namespaces: collision with chat tool names ───────────────────────────────

/** Chat tool names pinned by the mutation audit (not env-conditional registry loading), plus the dynamic ones. */
const CHAT_TOOL_NAMES = new Set<string>([...MUTATING_TOOL_NAMES, ...READ_ONLY_TOOL_NAMES, 'skill']);

describe('namespace collision (N10)', () => {
  test('the chat tool list is the one the spec names, so the check cannot silently go empty', () => {
    for (const n of ['tax_flag', 'edit_transaction', 'transaction_search', 'spending_summary', 'profit_loss', 'net_worth', 'categorize', 'budget_set']) {
      expect(CHAT_TOOL_NAMES.has(n), n).toBe(true);
    }
  });

  test('no WebMCP name equals a chat tool name', () => {
    expect(MCP_TOOL_CATALOG.map((d) => d.name).filter((n) => CHAT_TOOL_NAMES.has(n))).toEqual([]);
  });

  test('no WebMCP name starts with a dynamic chat prefix: chain_ team_ mcp_ skill', () => {
    for (const d of MCP_TOOL_CATALOG) expect(d.name, d.name).not.toMatch(/^(chain_|team_|mcp_|skill)/);
  });

  test('the six exact-string collisions the rename removes were all retired names', () => {
    const collided = [...CHAT_TOOL_NAMES].filter((n) => isRetiredToolName(n)).sort();
    expect(collided).toEqual(['edit_transaction', 'net_worth', 'profit_loss', 'spending_summary', 'tax_flag', 'transaction_search']);
  });
});

// ── Retired names (N11) ──────────────────────────────────────────────────────

describe('retired names (N11)', () => {
  const entries = Object.entries(RETIRED_TOOL_NAMES);

  test('15 pairs: 7 shipped in v0.9.x, 8 never shipped', () => {
    expect(entries).toHaveLength(15);
    expect(entries.filter(([, r]) => r.shipped).map(([o]) => o).sort()).toEqual(
      ['edit_transaction', 'forecast', 'net_worth', 'profit_loss', 'spending_summary', 'tax_flag', 'transaction_search']
    );
  });

  test('the map is injective, every value is a current catalog name with the same classification, and no key is current', () => {
    const values = entries.map(([, r]) => r.name);
    expect(new Set(values).size).toBe(values.length);
    for (const [old, r] of entries) {
      expect(byName.has(old), `${old} is a current catalog name`).toBe(false);
      const def = byName.get(r.name);
      expect(def, r.name).toBeDefined();
      expect((baseline as Record<string, { classification: string }>)[old]!.classification, old).toBe(def!.classification);
    }
  });

  test('helpers: retiredNamesFor and currentNameFor invert each other; own-property lookups only', () => {
    for (const [old, r] of entries) {
      expect(currentNameFor(old)).toBe(r.name);
      expect(retiredNamesFor(r.name)).toContain(old);
    }
    expect(retiredNamesFor('categorize_transaction')).toEqual([]);
    expect(currentNameFor('__proto__')).toBeUndefined();
    expect(isRetiredToolName('constructor')).toBe(false);
  });

  test('getToolDef stays an exact match: no retired name resolves', async () => {
    const { getToolDef } = await import('../mcp/tool-catalog.js');
    for (const [old] of entries) expect(getToolDef(old), old).toBeUndefined();
  });
});

// ── I1: the rename changes nothing but names ─────────────────────────────────

type BaselineEntry = {
  classification: string; minRole: string; transports: string[]; surface: unknown; exposure: string;
  uiEffect: boolean | null; autosubmit: boolean | null; defaultPolicy: string; untrustedOutput: boolean;
  allowedPolicies: string[]; schemaDigest: string;
  readEstimates: Record<string, { rows: number; chars: number }> | null;
};
const BASE = baseline as unknown as Record<string, BaselineEntry>;
const currentOf = (old: string) => currentNameFor(old) ?? old;

describe('I1 baseline equivalence', () => {
  test('the baseline holds the 26 pre-rename names', () => {
    expect(Object.keys(BASE)).toHaveLength(26);
    expect(Object.keys(BASE).map(currentOf).sort()).toEqual(MCP_TOOL_CATALOG.map((d) => d.name).sort());
  });

  test('every attribute of def(new) equals baseline[old]', () => {
    for (const [old, b] of Object.entries(BASE)) {
      const d = byName.get(currentOf(old))!;
      const actual: unknown = {
          classification: d.classification, minRole: d.minRole, transports: [...d.transports], surface: d.surface,
          exposure: d.exposure, uiEffect: d.uiEffect ?? null, autosubmit: d.autosubmit ?? null,
          defaultPolicy: d.defaultPolicy, untrustedOutput: d.untrustedOutput, allowedPolicies: allowedPolicies(d),
        };
      const expected: unknown = {
        classification: b.classification, minRole: b.minRole, transports: b.transports, surface: b.surface,
        exposure: b.exposure, uiEffect: b.uiEffect, autosubmit: b.autosubmit,
        defaultPolicy: b.defaultPolicy, untrustedOutput: b.untrustedOutput, allowedPolicies: b.allowedPolicies,
      };
      expect(actual, old).toEqual(expected);
    }
  });

  test('digest unchanged for every http-mcp tool; the only changed digest is open_review_item (tab-only)', () => {
    const changed = Object.entries(BASE).filter(([old, b]) => schemaDigest(currentOf(old)) !== b.schemaDigest).map(([old]) => currentOf(old));
    expect(changed).toEqual(['open_review_item']);
    for (const name of changed) expect(byName.get(name)!.transports).not.toContain('http-mcp');
    for (const d of MCP_TOOL_CATALOG.filter((t) => t.transports.includes('http-mcp'))) {
      const old = Object.keys(BASE).find((o) => currentOf(o) === d.name)!;
      expect(schemaDigest(d.name), d.name).toBe(BASE[old]!.schemaDigest);
    }
  });
});

describe('I1b no retired name in catalog prose', () => {
  const UNDERSCORED = Object.keys(RETIRED_TOOL_NAMES).filter((n) => n.includes('_'));
  const exact = (name: string) => new RegExp(`(?<![A-Za-z0-9_])${name}(?![A-Za-z0-9_])`);

  const prose = (d: McpToolDef): string[] => [d.description, JSON.stringify(d.example), JSON.stringify(jsonSchemaFor(d.name))];

  test('descriptions, examples and zod .describe() strings', () => {
    for (const d of MCP_TOOL_CATALOG) {
      for (const text of prose(d)) {
        for (const old of UNDERSCORED) expect(exact(old).test(text), `${d.name} mentions ${old}`).toBe(false);
        expect(/`forecast`|use forecast|call forecast|forecast tool/.test(text), `${d.name} mentions the forecast tool`).toBe(false);
      }
    }
  });

  test('every error string in tool-catalog.ts (it is scanned as text)', () => {
    const text = readFileSync(join(import.meta.dir, '../mcp/tool-catalog.ts'), 'utf8');
    for (const old of UNDERSCORED) expect(exact(old).test(text), `tool-catalog.ts mentions ${old}`).toBe(false);
    expect(/`forecast`|use forecast|call forecast|forecast tool/.test(text)).toBe(false);
  });
});

// ── I13: no retired literal in runtime code ──────────────────────────────────

describe('I13 no retired literal in runtime code', () => {
  const SRC = join(import.meta.dir, '..');
  const UNDERSCORED = Object.keys(RETIRED_TOOL_NAMES).filter((n) => n.includes('_'));
  /** Chat, mirror, handoff and retired-name files: the places where these strings are the right vocabulary. */
  const ALLOWED = [
    'mcp/tool-names.ts',
    'mcp/judge-reads.ts',
    'mcp/confirmation-card.ts', // CHAT_TOOL_LABELS only
    'cli.ts',
  ];
  const ALLOWED_PREFIXES = [
    'dashboard/local-handoff', 'dashboard/ui/src/hybrid/', 'dashboard/ui/src/store/mirror-', 'dashboard/ui/src/store/sync-engine.ts',
    'tools/', 'agent/', 'skills/', 'orchestration/', 'components/', 'utils/', '__tests__/', 'dashboard/ui/node_modules/', 'dashboard/ui/dist/', 'dashboard/ui/spike/',
  ];

  function walk(dir: string, out: string[] = []): string[] {
    for (const e of readdirSync(dir)) {
      const p = join(dir, e);
      if (e === 'node_modules' || e === 'dist') continue;
      if (statSync(p).isDirectory()) walk(p, out);
      else if (/\.(ts|tsx)$/.test(e)) out.push(p);
    }
    return out;
  }

  test('no quoted or backticked retired name outside the allowed chat, mirror and handoff files', () => {
    const hits: string[] = [];
    let scanned = 0;
    for (const file of walk(SRC)) {
      const rel = relative(SRC, file);
      if (ALLOWED.includes(rel) || ALLOWED_PREFIXES.some((p) => rel.startsWith(p))) continue;
      scanned++;
      const text = readFileSync(file, 'utf8');
      for (const old of UNDERSCORED) {
        if (new RegExp(`(['"\`])${old}\\1`).test(text)) hits.push(`${rel}: ${old}`);
      }
    }
    expect(scanned).toBeGreaterThan(40); // the scan really ran over the mcp and dashboard sources
    expect(hits).toEqual([]);
  });
});

// ── I14: the read budget is unchanged ────────────────────────────────────────

describe('I14 readEstimate baseline equivalence', () => {
  test('every read tool reserves the same rows and characters as before the rename', () => {
    for (const [old, b] of Object.entries(BASE)) {
      if (!b.readEstimates) continue;
      const d = byName.get(currentOf(old))!;
      const actual: unknown = { empty: readEstimate(d, {}), limit7: readEstimate(d, { limit: 7 }), balance_sheet: readEstimate(d, { action: 'balance_sheet' }) };
      expect(actual, old).toEqual(b.readEstimates as unknown);
    }
  });

  test('get_net_worth balance_sheet reserves its full page size, not the default limit', () => {
    expect(readEstimate(byName.get('get_net_worth')!, { action: 'balance_sheet' }).rows).toBe(15);
    expect(readEstimate(byName.get('get_net_worth')!, {}).rows).toBe(10);
  });
});

// ── I11: the mirror boundary ─────────────────────────────────────────────────

describe('I11 mirror and router boundary', () => {
  test('HANDOFF_TO_CATALOG covers READ_TOOL_NAMES exactly and every value is a read catalog tool', () => {
    expect(Object.keys(HANDOFF_TO_CATALOG).sort()).toEqual([...READ_TOOL_NAMES].sort());
    for (const catalogName of Object.values(HANDOFF_TO_CATALOG)) expect(byName.get(catalogName)?.classification, catalogName).toBe('read');
  });

  test('READ_TOOL_SCHEMAS[m] deep-equals jsonSchemaFor(HANDOFF_TO_CATALOG[m])', () => {
    for (const m of READ_TOOL_NAMES) {
      expect(READ_TOOL_SCHEMAS[m] as unknown, m).toEqual(JSON.parse(JSON.stringify(jsonSchemaFor(HANDOFF_TO_CATALOG[m]))));
    }
  });

  test('the boundary map is not the retired-name map: its values are the retired map\'s values for the same tool', () => {
    for (const m of READ_TOOL_NAMES) expect(currentNameFor(m)).toBe(HANDOFF_TO_CATALOG[m]);
  });
});
