/**
 * Generates src/mcp/unicode-fold-table.ts, the per-code-point fold used instead of String.prototype.normalize().
 *
 * Why a table: normalize() on attacker-controlled text is a denial of service. ICU reorders canonical combining
 * classes quadratically, and every "stream-safe" pre-pass we tried had a bypass (U+FF9E / U+FF9F are category Lm,
 * not \p{M}, yet NFKC-map to U+3099 / U+309A, ccc 8). A per-code-point lookup has no cross-character state, so it cannot
 * be quadratic. This script is the ONLY place in the repo allowed to call normalize() (a source-guard test enforces it).
 *
 * Output is deterministic for a given Unicode version (recorded in the file header; process.versions.unicode).
 * Usage: bun scripts/gen-unicode-fold-table.ts
 */
import { writeFileSync } from 'node:fs';
import { join } from 'node:path';

const hex = (s: string): string => [...s].map((c) => c.codePointAt(0)!.toString(16).toUpperCase()).join(' ');

const fold: string[] = []; // "CP>HEX HEX"
const strip: string[] = []; // "CP>ascii alnum" (NFD base letters with marks removed)
const bracketOpen: number[] = [];
const bracketClose: number[] = [];

for (let cp = 0; cp <= 0x10ffff; cp++) {
  if (cp >= 0xd800 && cp <= 0xdfff) continue;
  const ch = String.fromCodePoint(cp);
  const k = ch.normalize('NFKC'); // single code point: no reordering happens, this runs once at generation time
  if (k !== ch) {
    fold.push(`${cp.toString(16).toUpperCase()}>${hex(k)}`);
    if (k.includes('[')) bracketOpen.push(cp);
    if (k.includes(']')) bracketClose.push(cp);
  }
  // NFD base letters, marks removed, kept only when the result is plain ASCII letters/digits (all the marker check can match).
  const d = ch.normalize('NFD');
  if (d !== ch) {
    const base = d.replace(/\p{M}/gu, '');
    if (base !== ch && /^[A-Za-z0-9]+$/.test(base)) strip.push(`${cp.toString(16).toUpperCase()}>${base}`);
  }
}

const list = (a: number[]): string => a.map((c) => c.toString(16).toUpperCase()).join(' ');
const out = `// GENERATED by scripts/gen-unicode-fold-table.ts. DO NOT EDIT. Regenerate with: bun scripts/gen-unicode-fold-table.ts
// Unicode ${process.versions.unicode} (ICU ${process.versions.icu}); ${fold.length} fold entries, ${strip.length} strip entries.

/** Unicode version the tables were generated from. */
export const UNICODE_FOLD_VERSION = ${JSON.stringify(process.versions.unicode)};

/** "CP>CP CP ..." (hex): NFKC of that single code point, for every code point where it differs from the code point. */
export const FOLD_DATA = ${JSON.stringify(fold.join(';'))};

/** "CP>letters": the plain ASCII letters/digits left after NFD and removing marks, for precomposed letters. */
export const STRIP_DATA = ${JSON.stringify(strip.join(';'))};

/** Code points whose fold contains "[" / "]" (full width, small, ... brackets), hex separated by spaces. */
export const FOLD_OPEN_BRACKET_CPS = ${JSON.stringify(list(bracketOpen))};
export const FOLD_CLOSE_BRACKET_CPS = ${JSON.stringify(list(bracketClose))};
`;
writeFileSync(join(import.meta.dir, '..', 'src', 'mcp', 'unicode-fold-table.ts'), out);
console.log(`wrote ${fold.length} fold, ${strip.length} strip, ${bracketOpen.length}+${bracketClose.length} bracket entries (Unicode ${process.versions.unicode})`);
